version: "3.7"
services:
  mongodb:
    image: mongo:latest
    restart: on-failure
    env_file: .env
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

  trips:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    restart: on-failure
    env_file: .env
    volumes:
      - ".:/myapp"
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
